drop table T_SHOPPING_QNA;

CREATE TABLE T_SHOPPING_QNA
(
    "QNA_ID" NUMBER(20,0) PRIMARY KEY,
    "GOODS_ID" NUMBER(20,0),
    "MEMBER_ID" VARCHAR2(10 BYTE),
    "QNA_TITLE" VARCHAR2(100 BYTE),
    "QNA_CONTENT" VARCHAR2(1000 BYTE) DEFAULT 'N',
    "QNA_DATE" DATE DEFAULT sysdate,
    CONSTRAINT "FK_MEMBER_ID" FOREIGN KEY ("MEMBER_ID")
        REFERENCES "SCOTT"."T_SHOPPING_MEMBER" ("MEMBER_ID"),
    CONSTRAINT "FK_GOODS_ID" FOREIGN KEY ("GOODS_ID")
        REFERENCES "SCOTT"."T_SHOPPING_GOODS" ("GOODS_ID")
);
    
    
insert into T_SHOPPING_QNA (QNA_id,GOODS_id,MEMBER_id,QNA_title,QNA_content,QNA_date) values
( ( SELECT NVL(MAX(QNA_id), 0) +1 FROM T_SHOPPING_QNA),354, 'lee',
  'QNA 제목입니다6.',
  'QNA 내용입니다6.',
  sysdate );
    
select * from T_SHOPPING_QNA;

SELECT Q.QNA_ID, Q.MEMBER_ID, M.MEMBER_NAME, Q.QNA_TITLE, Q.QNA_CONTENT, Q.QNA_DATE
FROM T_SHOPPING_QNA Q
JOIN T_SHOPPING_MEMBER M ON Q.MEMBER_ID = M.MEMBER_ID;

SELECT
    Q.QNA_ID,
    I.FILENAME,
    Q.QNA_TITLE,
    M.MEMBER_NAME,
    Q.QNA_DATE
FROM
    T_SHOPPING_QNA Q
    JOIN T_SHOPPING_GOODS G ON Q.GOODS_ID = G.GOODS_ID
    JOIN T_SHOPPING_MEMBER M ON Q.MEMBER_ID = M.MEMBER_ID
    JOIN T_GOODS_DETAIL_IMAGE I ON G.GOODS_ID = I.GOODS_ID
WHERE I.FILETYPE = 'main_image';

SELECT * FROM T_SHOPPING_QNA WHERE qna_id = 4;
SELECT * FROM T_SHOPPING_QNA WHERE
qna_title like '%'||'QNA'||'%' OR
qna_content like '%'||'QNA'||'%'
order by qna_id desc;

SELECT * FROM (
    SELECT temp_table.*, ROWNUM AS rnum FROM (
        SELECT Q.QNA_ID, I.FILENAME, Q.QNA_TITLE, M.MEMBER_NAME, Q.QNA_DATE, G.GOODS_ID
        FROM T_SHOPPING_QNA Q
        JOIN T_SHOPPING_GOODS G ON Q.GOODS_ID = G.GOODS_ID
        JOIN T_SHOPPING_MEMBER M ON Q.MEMBER_ID = M.MEMBER_ID
        JOIN T_GOODS_DETAIL_IMAGE I ON G.GOODS_ID = I.GOODS_ID
        WHERE I.FILETYPE = 'main_image'
        ORDER BY Q.QNA_ID DESC
    ) temp_table ) WHERE RNUM BETWEEN 1 AND 10;

commit;